# Generated by Django 3.1.6 on 2021-02-15 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_example', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='amusementparkprebooking',
            name='prebooking_ref',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='museumprebooking',
            name='prebooking_ref',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurantprebooking',
            name='prebooking_ref',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
